seed: 5
torch_deterministic: False

preference_encoder:
  name: vits-mae-hoi
  pretrain_dir: "/home/thomastian/workspace/mvp_exp_data/mae_encoders/"
  freeze: True
  emb_dim: 128

policy:
  pi_hid_sizes: [256, 128, 64]
  vf_hid_sizes: [256, 128, 64]

learn:
  agent_name: kuka_ppo
  test: False
  resume: 0
  save_interval: 50
  print_log: True

  max_iterations: 2000

  cliprange: 0.1
  ent_coef: 0
  nsteps: 45
  noptepochs: 10
  nminibatches: 4
  max_grad_norm: 1
  optim_stepsize: 0.001
  schedule: cos
  gamma: 0.99
  lam: 0.95
  init_noise_std: 1.0

  log_interval: 1

  reward_type: 'ground_truth'
  encoder_type: 'vit'